#!/usr/bin/env bash
# Installed nginx on my web-01 server
# Nginx should was listening on port 80
# Querying Nginx at its root / with a GET request (requesting a page) 
# using curl, return a page that contains the string Hello World

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx reload
