#!/usr/bin/env bash
# Bash script that findout what’s keeping your Ubuntu container’s Nginx installation from listening on port 8?
# The script below configures nginx to run and listen to port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
